from __future__ import annotations


class StopwordsFilter:
    """
    Filtro de stopwords em português.
    Inclui uma lista nativa leve para evitar dependência obrigatória do NLTK/spaCy.
    """

    # Lista compilada com base nas stopwords comuns do NLTK para PT-BR
    DEFAULT_STOPWORDS = {
        "a",
        "ao",
        "aos",
        "aquela",
        "aquelas",
        "aquele",
        "aqueles",
        "aquilo",
        "as",
        "ate",
        "com",
        "como",
        "da",
        "das",
        "de",
        "dela",
        "delas",
        "dele",
        "deles",
        "depois",
        "do",
        "dos",
        "e",
        "ela",
        "elas",
        "ele",
        "eles",
        "em",
        "entre",
        "era",
        "eram",
        "eramos",
        "essa",
        "essas",
        "esse",
        "esses",
        "esta",
        "estas",
        "estavam",
        "estavamos",
        "este",
        "esteja",
        "estejam",
        "estejamos",
        "estes",
        "esteve",
        "estive",
        "estivemos",
        "estiver",
        "estivera",
        "estiveram",
        "estiveramos",
        "estiverem",
        "estivermos",
        "estivesse",
        "estivessem",
        "estivessemos",
        "estou",
        "eu",
        "foi",
        "fomos",
        "for",
        "fora",
        "foram",
        "foramos",
        "forem",
        "formos",
        "fosse",
        "fossem",
        "fossemos",
        "fui",
        "ha",
        "haja",
        "hajam",
        "hajamos",
        "hao",
        "havemos",
        "hei",
        "houve",
        "houvemos",
        "houver",
        "houvera",
        "houveram",
        "houveramos",
        "houverem",
        "houvermos",
        "houvesse",
        "houvessem",
        "houvessemos",
        "isso",
        "isto",
        "ja",
        "lhe",
        "lhes",
        "mais",
        "mas",
        "me",
        "mesmo",
        "meu",
        "meus",
        "minha",
        "minhas",
        "muito",
        "na",
        "nao",
        "nas",
        "nem",
        "no",
        "nos",
        "nossa",
        "nossas",
        "nosso",
        "nossos",
        "num",
        "numa",
        "o",
        "os",
        "ou",
        "para",
        "pela",
        "pelas",
        "pelo",
        "pelos",
        "por",
        "qual",
        "quando",
        "que",
        "quem",
        "sao",
        "se",
        "seja",
        "sejam",
        "sejamos",
        "sem",
        "serei",
        "seremos",
        "seria",
        "seriam",
        "seriamos",
        "seu",
        "seus",
        "so",
        "somos",
        "sou",
        "sua",
        "suas",
        "tambem",
        "te",
        "tem",
        "temos",
        "tenha",
        "tenham",
        "tenhamos",
        "tenho",
        "tera",
        "terao",
        "terei",
        "teremos",
        "teria",
        "teriam",
        "teriamos",
        "teu",
        "teus",
        "teve",
        "tinha",
        "tinham",
        "tinhamos",
        "tive",
        "tivemos",
        "tiver",
        "tivera",
        "tiveram",
        "tiveramos",
        "tiverem",
        "tivermos",
        "tivesse",
        "tivessem",
        "tivessemos",
        "tu",
        "tua",
        "tuas",
        "um",
        "uma",
        "voce",
        "voces",
        "vos",
    }

    def __init__(
        self, use_default: bool = True, custom_stopwords: set[str] | None = None
    ):
        self._stopwords = set()
        if use_default:
            self._stopwords.update(self.DEFAULT_STOPWORDS)
        if custom_stopwords:
            self._stopwords.update(custom_stopwords)

    def filter(self, tokens: list[str]) -> list[str]:
        """
        Recebe uma lista de tokens limpados (sem acento, minúsculos, etc)
        e retorna uma nova lista sem as stopwords.
        Preserva as tags de entidade (<money:10> etc).
        """
        # Tags de entidade e números não são stopwords
        # E só verificamos a igualdade exata na lista de stopwords
        return [t for t in tokens if t not in self._stopwords or t.startswith("<")]
